include:
  - greetings/*
kind: ArchiveUploadSpec
name: greetings-FHg0

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: greetings-569425c1-113d-4e74-9b72-2871dc1ebec0
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://greetings-FHg0
status:
  buildstatus: pending
  lastUpdateTimestamp: "2021-06-21T07:01:14Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: greetings
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: hello.main
    packageref:
      name: greetings-569425c1-113d-4e74-9b72-2871dc1ebec0
      namespace: default
  requestsPerPod: 1
  resources: {}
