apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: b45a446a-f3ef-4704-bfdb-2ad400348f80
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: greetings
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /greetings
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /greetings
